version: "3.9"
services:
  app:
    build: .
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      DB_HOST: postgres
      DB_USER: $POSTGRESDB_USER
      DB_PASSWORD: $POSTGRESDB_ROOT_PASSWORD
      DB_NAME: $POSTGRESDB_DATABASE
      DB_PORT: $POSTGRESDB_DOCKER_PORT
    depends_on:
      postgres:
        condition: service_started
    networks:
      - dev-network

  postgres:
    image: postgres:alpine
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_USER: $POSTGRESDB_USER
      POSTGRES_PASSWORD: $POSTGRESDB_ROOT_PASSWORD
      POSTGRES_DB: $POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - dev-network
networks:
  dev-network:
volumes:
  pg_data:
